name: 'job_market_pipeline'
version: '1.0.0'
config-version: 2

# This name must match the name in profiles.yml
profile: 'job_market_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  job_market_pipeline:
    # Silver Layer
    staging:
      +schema: staging
      +materialized: view
    # Gold Layer
    marts:
      +schema: marts
      +materialized: table