job_market_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: "{{ env_var('DB_PASSWORD') }}" # dbt will pull this from .env file
      dbname: job_pipeline
      schema: public
      threads: 4